<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * DrankSoortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrankSoortRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function findAllOrderedByName()
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT ds FROM AppBundle:DrankSoort ds ORDER BY ds.naam ASC'
				)
				->getResult();
	}

	public function findAllOrderedBySMSPos()
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT ds FROM AppBundle:DrankSoort ds ORDER BY ds.smspositieid ASC'
			)
			->getResult();
	}
	public function findAllWithEenheidAndOrderedByName()
	{
		return $this->queryAllWithEenheidAndSortedBy("naam")->execute();
	}
	/**
	 * Returns the query to retrieve all the bundles with their associated owners
	 * and contributors, sorted by the specified field
	 *
	 * @param  string $field The name of the field to sort by
	 *
	 * @return \Doctrine\ORM\Query
	 */
	public function queryAllWithEenheidAndSortedBy($field)
	{
		$q = $this->createQueryBuilder('dranksoort')
		->select('dranksoort, drankeenheid')
		->leftJoin('dranksoort.eenheid', 'drankeenheid')
		->addOrderBy('dranksoort.' . $field, 'name' === $field ? 'asc' : 'desc')
		->getQuery();
	
		return $q;
	}
	
}
