<?php
// src/AppBundle/Entity/User.php

namespace AppBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber as AssertPhoneNumber;
use libphonenumber\PhoneNumber;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 * @ORM\HasLifecycleCallbacks()
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    /**
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Group")
     * @ORM\JoinTable(name="fos_user_user_group",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $groups;

    /**
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\SmsNotifType")
     * @ORM\JoinTable(name="fos_user_smsnotifs",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="smsnotif_id", referencedColumnName="id")}
     * )
     */
    protected $smsnotifys;

    /**
     * @ORM\Column(type="boolean")
     *
     */
    protected $manager;

    /**
     * @ORM\Column(type="phone_number", unique=true)
     * @AssertPhoneNumber(type="mobile")
     *
     */
    protected $gsm_app;

    /**
     * @ORM\Column(type="phone_number", unique=true)
     * @AssertPhoneNumber(type="mobile")
     */
    protected $gsm_perso;


    /**
     * created Time/Date
     *
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=false)
     */
    protected $createdAt;

    /**
     * updated Time/Date
     *
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=false)
     */
    protected $updatedAt;

    public function getRoles()
    {
        return parent::getRoles(); // TODO: Change the autogenerated stub
    }


    public function __construct()
    {
        parent::__construct();
        $this->smsnotifys = new ArrayCollection();
    }


    /**
     * Set gsmApp
     *
     * @param AssertPhoneNumber $gsmApp
     *
     * @return User
     */
    public function setGsmApp($gsmApp)
    {

        $this->gsm_app = $gsmApp;

        return $this;
    }

    /**
     * Get gsmApp
     *
     * @return AssertPhoneNumber
     */
    public function getGsmApp()
    {
        return $this->gsm_app;
    }

    /**
     * Set gsmPerso
     *
     * @param AssertPhoneNumber $gsmPerso
     *
     * @return UserOld
     */
    public function setGsmPerso($gsmPerso)
    {
        $this->gsm_perso = $gsmPerso;

        return $this;
    }

    /**
     * Get gsmPerso
     *
     * @return AssertPhoneNumber
     */
    public function getGsmPerso()
    {
        return $this->gsm_perso;
    }


    /**
     * Set createdAt
     *
     * @ORM\PrePersist
     */
    public function setCreatedAt()
    {
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();

    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @ORM\PreUpdate
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = new \DateTime();

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set groups
     *
     * @param ArrayCollection $groups
     * @return User
     */

    public function setGroups(ArrayCollection $groups)
    {
        $this->groups = $groups;

        return $this;
    }

    /**
     * Add od
     *
     * @param \AppBundle\Entity\SmsNotifType
     *
     * @return User
     */
    public function addSmsnotify(\AppBundle\Entity\SmsNotifType $smsnotify)
    {

        $this->smsnotifys[] = $smsnotify;
        return $this;
    }

    /**
     * Remove od
     *
     * @param \AppBundle\Entity\SmsNotifType $smsnotify
     */
    public function removeSmsnotify(\AppBundle\Entity\SmsNotifType $smsnotify)
    {

        $this->smsnotifys->removeElement($smsnotify);
    }

    /**
     * @return mixed
     */
    public function getSmsnotifys()
    {
        return $this->smsnotifys;
    }

    /**
     * @param mixed $smsnotifys
     */
    public function setSmsnotifys($smsnotifys)
    {
        $this->smsnotifys = $smsnotifys;
    }

    /**
     * @return mixed
     */
    public function getManager()
    {
        return $this->manager;
    }

    /**
     * @param mixed $manager
     */
    public function setManager($manager)
    {
        $this->manager = $manager;
    }


}
